base/urls.py
from django.urls import path, include
from django.conf.urls import handler404
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout', views.logout_user, name="logout_user"),
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name="register"),
    #path("book/<str:title>/", views.book, name="book"),
    path("books/", views.books, name="books"),
    path("bookform/", views.bookform, name="bookform"),
    path("bookform/<int:pk>/", views.edit_book, name="edit_book"),
    path("readform/", views.readform, name="readform"),
    path("unapproved_reads/", views.unapproved_books, name="unapproved_books"),
    path("approve_book/<int:pk>/", views.approve_book, name="approve_book"),
    path("deny_book/<int:pk>/", views.deny_book, name="deny_book"),
    path("books/<str:name>/", views.specific_book, name="book"),
    path("ratings/", views.ratings, name="ratings"),
    path("edit_rating/<int:rating_id>/", views.edit_rating, name="edit_rating"),
    path("delete_rating/<int:rating_id>/", views.delete_rating, name="delete_rating"),
    path("profile/", views.profile, name="user_profile"),
    path("profile/edit", views.edit_profile, name="edit_profile"),
    path("profile/<str:name>/", views.view_profile, name="profile"),
    path("change_password/", views.change_password, name="change_password")
]

handler404 = views.custom_404_view

boekenclub/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls"))
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone


class Book(models.Model):
    title = models.TextField()
    author = models.TextField()
    genre = models.TextField()
    number_of_pages = models.IntegerField(
        blank=False,
        validators=[
            MinValueValidator(1, message="Waarde moet groter dan of gelijk zijn aan 1!"),
            MaxValueValidator(4032, message="Er bestaat geen boek met meer dan 4032 pagina's!")]
    )
    approved = models.BooleanField(default=False)
    approved_by = models.ForeignKey(User, on_delete=models.CASCADE,
                                    related_name='approved_by', null=True, blank=True)
    def __str__(self):
        return self.title
    

class Read(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    date = models.DateTimeField(null=True, blank=True)
    score = models.IntegerField(
            blank=False,
            validators=[
                MinValueValidator(0, message="Waarde moet grooter of gelijk zijn aan 0"),
                MaxValueValidator(10, message="Waarde moet kleiner dan of gelijk zijn aan 10")
            ])

class Profile(models.Model):
    biotext = models.TextField()
    date_of_birth = models.DateField(null=True, blank=True)
    city = models.TextField(null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

base/forms.py
from django import forms
from .models import Profile, Read, Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ("title", "author", "genre", "number_of_pages")
        labels = {
            'title': 'Titel',
            'author': 'Auteur',
            'genre': 'Genre',
            'number_of_pages': 'Aantal Pagina\'s',
        }


class ReadForm(forms.ModelForm):
    class Meta:
        model = Read
        fields = ("book", "date", "score")
        widgets = {
            'date': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'type': 'datetime-local'
                    }),
        }
        labels = {
            'book': 'Boek',
            'date': 'Datum',
            'score': 'Score',
        }


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("biotext", "city", "date_of_birth")
        widgets = {
            'date_of_birth': forms.DateInput(
                attrs={
                    'class': 'form-control',
                    'type': 'date'
                    }),
        }
        labels = {
            'biotext': 'Bio',
            'city': 'Woonplaats',
            'date_of_birth': 'Geboortedatum',
        }

base/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.forms import UserCreationForm, SetPasswordForm
from django.contrib.auth import login, logout, update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.admin.views.decorators import staff_member_required
from django.db.models import Min, Max, Avg
from .models import Profile, Book, Read
from .forms import ReadForm, BookForm, ProfileForm
from django.db.models import Q

def index(request):
    return render(request, "base/index.html")

@login_required
def readform(request):
    book_id = request.GET.get("book")

    if request.method == "POST":
        form = ReadForm(request.POST)
        if form.is_valid():
            read = form.save(commit=False)
            read.user = request.user

            if Read.objects.filter(user=request.user, book=read.book, date=read.date).exists():
                messages.error(request, "Je hebt dit boek al gelezen op deze datum!")
                return redirect("ratings")

            read.save()
            messages.success(request, "Beoordeling succesvol toegevoegd")
            return redirect("ratings")
    else:
        initial_data = {}
        if book_id:
            initial_data["book"] = book_id
        form = ReadForm(initial=initial_data)

    context = {"form": form}

    return render(request, "base/add_form.html", context)


@staff_member_required
def edit_book(request, pk):
    book = get_object_or_404(Book, pk=pk)

    if request.method == "POST":
        form = BookForm(request.POST, instance=book)

        if "delete" in request.POST:
            book.delete()
            messages.success(request, "Boek verwijderd")
            return redirect("books")

        if form.is_valid():
            form.save()
            messages.success(request, "Boek succesvol aangepast")
            return redirect("books")
    else:
        form = BookForm(instance=book)

    context = {
        "form": form,
        "edit": True,
        "book": book,
    }
    return render(request, "base/edit_book.html", context)

@login_required
def bookform(request):
    if request.method == "POST":
        form = BookForm(request.POST)
        if form.is_valid():
            book = form.save(commit=False)
            if request.user.is_staff:
                book.approved = True
            book.user = request.user
            book.save()
            messages.success(request, "Boek succesvol toegevoegd")
            return redirect("books")
    else:
        form = BookForm()

    context = {"form": form, "user": request.user}
    return render(request, "base/add_form.html", context)

@staff_member_required
def unapproved_books(request):
    books = Book.objects.filter(approved=False)

    context = {"books": books}
    return render(request, "base/unapproved_books.html", context)

@staff_member_required
def approve_book(request, pk):
    book = Book.objects.get(pk=pk)
    book.approved = True
    book.approved_by = request.user
    book.save()
    messages.success(request, "Boek goedgekeurd")
    return redirect("unapproved_books")

@staff_member_required
def deny_book(request, pk):
    book = Book.objects.get(pk=pk)
    book.delete()
    messages.success(request, "Boek afgekeurd")
    return redirect("unapproved_books")

def register(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("index")
    else:
        form = UserCreationForm()

    context = {"form": form}
    return render(request, "registration/register.html", context)

@login_required
def logout_user(request):
    logout(request)
    return redirect('login')

@login_required
def books(request):
    books = Book.objects.filter(approved=True)

    context = {"books": books, "total": books.count()}
    return render(request, "base/approved_books.html", context)


@login_required
def specific_book(request, name: str):
    book = Book.objects.get(title=name)
    readings = Read.objects.filter(book=book)
    average_score = readings.aggregate(Avg('score'))['score__avg']
    
    if average_score:
        total_stars = []
        stars = average_score / 2
        for i in range(1, 6):
            if stars >= i:
                total_stars.append("full")
            elif stars >= i - 0.5:
                total_stars.append("half")
            else:
                total_stars.append("empty")

        context = {"book": book,
                'reads': readings.count(),
                'average': total_stars}
    else:
        context = {"book": book,
                'reads': readings.count()}

    return render(request, "base/specific_book.html", context)

@login_required
def ratings(request):
    all_ratings = Read.objects.select_related("book", "user").order_by("-date")

    for read in all_ratings:
        stars = []
        score = read.score / 2 
        for i in range(1, 6):
            if score >= i:
                stars.append("full")
            elif score >= i - 0.5:
                stars.append("half")
            else:
                stars.append("empty")
        read.star_images = stars

    context = {
        "ratings": all_ratings,
        "total": all_ratings.count(),
    }

    return render(request, "base/ratings.html", context)

@login_required
@staff_member_required
def delete_rating(request, rating_id):
    if request.method == 'POST':
        rating = Read.objects.filter(pk=rating_id)
        rating.delete()
    
    return redirect('ratings')

def edit_rating(request, rating_id):
    rating = get_object_or_404(Read, pk=rating_id)

    if request.method == "POST":
        form = ReadForm(request.POST, instance=rating)
        if form.is_valid():
            form.save()
            messages.success(request, "Beoordeling succesvol bewerkt")
            return redirect("user_profile")
    else:
        form = ReadForm(instance=rating)

    context = {"form": form, "edit": True}
    return render(request, "base/edit_rating.html", context)


def custom_404_view(request, exception):
    return render(request, "base/404.html", status=404)

@login_required
def view_profile(request, name: str):
    try:
        user = User.objects.get(username=name)
        profile = Profile.objects.get(user=user)
        all_ratings = Read.objects.select_related("book", "user").filter(user=user).order_by("-date")
    except:
        return redirect("ratings")

    for read in all_ratings:
        stars = []
        score = read.score / 2 
        for i in range(1, 6):
            if score >= i:
                stars.append("full")
            elif score >= i - 0.5:
                stars.append("half")
            else:
                stars.append("empty")
        read.star_images = stars

    context = {
        "profile": profile,
        "ratings": all_ratings,
        "total": all_ratings.count(),
        "edit": False
    }
    return render(request, "base/profile.html", context)
    
@login_required
def profile(request):
    all_ratings = Read.objects.select_related("book", "user").filter(user=request.user).order_by("-date")
    try:
        profile = Profile.objects.get(user=request.user)
    except Profile.DoesNotExist:
        profile = None

    for read in all_ratings:
        stars = []
        score = read.score / 2 
        for i in range(1, 6):
            if score >= i:
                stars.append("full")
            elif score >= i - 0.5:
                stars.append("half")
            else:
                stars.append("empty")
        read.star_images = stars

    context = {
        "profile": profile,
        "ratings": all_ratings,
        "total": all_ratings.count(),
        "edit": False
    }
    return render(request, "base/profile.html", context)

@login_required
def edit_profile(request):
    profile = get_object_or_404(Profile, user=request.user)

    if request.method == "POST":
        form = ProfileForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Profiel succesvol bewerkt")
            return redirect("user_profile")
    else:
        form = ProfileForm(instance=profile)

    context = {
        "form": form,
        "edit": True
    }
    return render(request, "base/profile.html", context)

@login_required
def change_password(request):
    if request.method == 'POST':
        form = SetPasswordForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('user_profile')
    else:
        form = SetPasswordForm(user=request.user)
    return render(request, 'base/add_form.html', {'form': form})

base/templates/base/add_form.html
{% extends "base/base.html" %}

{% block content %}
    <div class="add-form">
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="buttons">
                <input type="submit" value="Submit" class="submit">
                {% if edit %}
                    {% if user.is_staff %}
                        <input type="submit" name="delete" value="Delete" class="submit">
                    {% endif %}
                {% endif %}
            </div>
        </form>
    </div>
{% endblock content %}

base/templates/base/approved_books.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<h1>Alle Boeken</h1> <br>
<a class="link2" href="{% url 'bookform' %}">Voeg een boek toe</a>

{% for book in books %}
    <div class="rating-comment">
        <div class="rating-meta">
            <a class="link3" href="{% url 'book' book.title %}">{{book.title}}</a>
            {% if user.is_staff %}
                <form action="{% url 'edit_book' book.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="delete-button">
                        <img src="{% static "base/img/edit.png" %}" alt="Verwijder">
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="rating-book<">
            Boek: <strong>{{ book.title }}</strong><br>
            Auteur: <strong>{{ book.author }}</strong><br>
            Genre: <strong>{{ book.genre }}</strong><br>
            Pagina's: <strong>{{ book.number_of_pages }}</strong>
        </div>
    </div>
{% empty %}
    <p><strong>Er zijn op dit moment geen goedgekeurde boeken.</strong></p>
{% endfor %}
{% endblock content %}

base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} De Geletterde Kat{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'base/css/styles.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static "base/img/plaatje_groot.png" %}">
    {% block csslinks %}{% endblock csslinks%}
</head>
<body>
    {% include "base/menu.html" %}

    {% if messages %}
        <div class="messages">
            {% for message in messages %}
                {{message}}<br>
            {% endfor %}
        </div>
    {% endif %}
    <div class="content">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

base/templates/base/edit_book.html
{% extends "base/base.html" %}

{% block content %}
    <div class="add-form">
        <h2>Boek bewerken: {{ book.title }}</h2>
        <form method="POST">
            {% csrf_token %}
        
            <p>
                <label for="id_title">Titel:</label>
                <input type="text" name="title" id="id_title" value="{{ form.instance.title }}">
            </p>
        
            <p>
                <label for="id_author">Auteur:</label>
                <input type="text" name="author" id="id_author" value="{{ form.instance.author }}">
            </p>
        
            <p>
                <label for="id_genre">Genre:</label>
                <input type="text" name="genre" id="id_genre" value="{{ form.instance.genre }}">
            </p>
        
            <p>
                <label for="id_number_of_pages">Aantal Pagina's:</label>
                <input type="number" name="number_of_pages" id="id_number_of_pages" value="{{ form.instance.number_of_pages }}">
            </p>
        
            <div class="buttons">
                <input type="submit" value="Opslaan" class="submit">
                {% if edit and user.is_staff %}
                    <input type="submit" name="delete" value="Verwijder" class="submit">
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

base/templates/base/edit_rating.html
{% extends "base/base.html" %}

{% block content %}
    <div class="add-form">
        <h2>Beoordeling bewerken:</h2>
        <form method="POST">
            {% csrf_token %}
        
            <p>
                <label for="id_book">Boek:</label>
                <select name="book" id="id_book">
                    {% for book in form.book.field.queryset %}
                        <option value="{{ book.id }}" {% if book.id == form.instance.book.id %}selected{% endif %}>
                            {{ book.title }}
                        </option>
                    {% endfor %}
                </select>
            </p>
        
            <p>
                <label for="id_date">Datum:</label>
                <input type="datetime-local" name="date" id="id_date" value="{{ form.instance.date|date:'Y-m-d\TH:i' }}">
            </p>
        
            <p>
                <label for="id_score">Score:</label>
                <input type="number" name="score" id="id_score" min="1" max="10" value="{{ form.instance.score }}">
            </p>
        
            <div class="buttons">
                <input type="submit" value="Opslaan" class="submit">
                {% if edit %}
                    <input type="submit" name="delete" value="Verwijder" class="submit">
                {% endif %}
            </div>
        </form>
    </div>
{% endblock %}

base/templates/base/index.html
{% extends "base/base.html" %}
{% load static%}

{% block content %}
<p>Welkom bij de website van Boekenclub De Geletterde Kat!</p>
{% endblock content %}

base/templates/base/menu.html
{% load static %}

<div class="menu">
    <div class="menu-top">
        <img class="logo" src="{% static "base/img/plaatje.png" %}" alt="Logo">
        <h1 class="title">Boekenclub De Geletterde Kat</h1>
    </div>
    <div class="menu-bottom">
        {% if user.is_authenticated %}
            <seperator>
            <a class="link" href="{% url 'index' %}">Home</a>
            <a class="link" href="{% url 'ratings' %}">Beoordelingen</a>
            <a class="link" href="{% url 'books' %}">Boeken</a>
            {% if user.is_staff %}
                <a class="link" href="{% url 'unapproved_books' %}">Ongekeurde Boeken</a>
            {% endif %}
            <a href="{% url 'logout_user' %}" class="link">Uitloggen</a>
        {% else %}
            <a href="{% url 'login' %}" class="link">Inloggen</a>
            <a href="{% url 'register' %}" class="link">Registreren</a>
        {% endif %}
    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'user_profile' %}">
            <img src="{% static 'base/img/profile.png' %}" alt="Profile" class="profile">
        </a>
    {% endif %}
</div>

base/templates/base/newread.html
{% extends "base/base.html" %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" class="submit">
    </form>
{% endblock content%}

base/templates/base/profile.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}

{% if edit %}
    <div class="profile-form">
        <h2>Profile</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" class="submit">
        </form>
    </div>
{% else %}
    <div class="profile-wrapper">
        <h2>Profile</h2>
        <div class="profile-data">
            Username: <strong>{{ profile.user }}</strong><br>
            Date of Birth: <strong>{{ profile.date_of_birth }}</strong><br>
            Woonplaats: <strong>{{ profile.city }}</strong><br>
            {% if profile.biotext %}
                Bio: <strong>{{ profile.biotext }}</strong><br>
            {% else %}
                Bio: <em>No bio provided.</em><br>
            {% endif %}
        </div>
        {% if user == profile.user %}
            <a class="link2" href="{% url 'edit_profile' %}">Edit Profile</a>
            <a class="link2" href="{% url 'change_password' %}">Change Password</a>
        {% endif %}
    <div>

    {% for rating in ratings %}
        <div class="rating-comment">
            <div class="rating-meta">
                <strong>{{rating.user.username}}</strong> - {{ rating.date }}
                {% if user.is_staff %}
                    <div class="admin-buttons">
                        <form action="{% url 'edit_rating' rating.id %}" method="POST" class="accept">
                            {% csrf_token %}
                            <button type="submit" class="approve-button">
                                <img src="{% static "base/img/edit.png" %}" alt="Accepteer">
                            </button>
                        </form>
                        <form action="{% url 'delete_rating' rating.id %}" method="POST" class="deny">
                            {% csrf_token %}
                            <button type="submit" class="delete-button">
                                <img src="{% static "base/img/trashcan.png" %}" alt="Negeer">
                            </button>
                        </form>
                    </div>
                {% endif %}
            </div>
            <div class="rating-book">
                <a class="link3" href="{% url 'book' rating.book.title %}">{{rating.book.title}}</a>
                Auteur: <strong>{{ rating.book.author }}</strong><br>
                Genre: <strong>{{ rating.book.genre }}</strong><br>
                Pagina's: <strong>{{ rating.book.number_of_pages }}</strong>
            </div>
            <div class="rating-stars">
                {% for star in rating.star_images %}
                    <img src="{% static 'base/img/star-'|add:star|add:'.png' %}" alt="{{ star }} star" class="star">
                {% endfor %}
            </div>
        </div>
    {% empty %}
        <p><strong>U heeft nog geen beoordelingen.</strong></p>
    {% endfor %}
{% endif %}
{% endblock content %}

base/templates/base/ratings.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<h1>Alle Beoordelingen</h1> <br>
<a class="link2" href="{% url 'readform' %}">Voeg een beoordeling toe</a>

{% for rating in ratings %}
    <div class="rating-comment">
        <div class="rating-meta">
            <a class="link3" href="{% url 'profile' rating.user.username %}">{{rating.user.username}}</a> - {{ rating.date }}
            {% if user.is_staff %}
                <form action="{% url 'delete_rating' rating.id %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="delete-button">
                        <img src="{% static "base/img/trashcan.png" %}" alt="Verwijder">
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="rating-book">
            <a class="link3" href="{% url 'book' rating.book.title %}">{{rating.book.title}}</a>
            Auteur: <strong>{{ rating.book.author }}</strong><br>
            Genre: <strong>{{ rating.book.genre }}</strong><br>
            Pagina's: <strong>{{ rating.book.number_of_pages }}</strong>
        </div>
        <div class="rating-stars">
            {% for star in rating.star_images %}
                <img src="{% static 'base/img/star-'|add:star|add:'.png' %}" alt="{{ star }} star" class="star">
            {% endfor %}
        </div>
    </div>
{% empty %}
    <p><strong>Er zijn op dit moment geen beoordelingen.</strong></p>
{% endfor %}
{% endblock content %}

base/templates/base/specific_book.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
    <br><br>
    <a class="link2" href="{% url 'readform' %}?book={{ book.id }}">Voeg een beoordeling toe</a>
    <div class="rating-comment">
        <div class="rating-meta">
            {{ book.title }}
            {% if user.is_staff %}
                <form action="{% url 'edit_book' book.pk %}" method="POST">
                    {% csrf_token %}
                    <button type="submit" class="delete-button">
                        <img src="{% static "base/img/edit.png" %}" alt="Verwijder">
                    </button>
                </form>
            {% endif %}
        </div>
        <div class="rating-book<">
            Auteur: <strong>{{ book.author }}</strong><br>
            Genre: <strong>{{ book.genre }}</strong><br>
            Pagina's: <strong>{{ book.number_of_pages }}</strong><br><br>
            {% if reads %}
                Dit boek heeft <strong>{{ reads }}</strong> beoordeling(en) en <br>heeft als gemiddelde beoordeling:<br>
            {% else %}
                Dit boek heeft nog geen beoordelingen.
            {% endif %}
        </div>
        {% if reads %}
            <div class="rating-stars">
                {% for star in average %}
                    <img src="{% static 'base/img/star-'|add:star|add:'.png' %}" alt="{{ star }} star" class="star">
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

base/templates/base/unapproved_books.html
{% extends "base/base.html" %}
{% load static %}

{% block content %}
<h1>Ongekeurde Boeken</h1> <br>
{% for book in books %}
    <div class="rating-comment">
        <div class="rating-meta">
            <strong>Er is een nieuw boek voorgesteld:</strong>
            {% if user.is_staff %}
                <div class="admin-buttons">
                    <form action="{% url 'approve_book' book.pk %}" method="POST" class="accept">
                        {% csrf_token %}
                        <button type="submit" class="approve-button">
                            <img src="{% static "base/img/accept.png" %}" alt="Accepteer">
                        </button>
                    </form>
                    <form action="{% url 'deny_book' book.pk %}" method="POST" class="deny">
                        {% csrf_token %}
                        <button type="submit" class="delete-button">
                            <img src="{% static "base/img/deny.png" %}" alt="Negeer">
                        </button>
                    </form>
                </div>
            {% endif %}
        </div>
        <div class="rating-book<">
            Boek: <strong>{{ book.title }}</strong><br>
            Auteur: <strong>{{ book.author }}</strong><br>
            Genre: <strong>{{ book.genre }}</strong><br>
            Pagina's: <strong>{{ book.number_of_pages }}</strong>
        </div>
    </div>
{% empty %}
    <p><strong>Er zijn op dit moment geen goedgekeurde boeken.</strong></p>
{% endfor %}
{% endblock content %}